// Generated by Wrangler by running `wrangler types src/types/worker-configuration.d.ts --env-interface WorkerEnv`

interface WorkerEnv {
	NODE_ENV: string;
	PORTAL_URL: string;
	DIRECTUS_URL: string;
	DIRECTUS_SECRET_KEY: string;
	DIRECTUS_SERVICE_TOKEN: string;
	DIRECTUS_SIGNED_URL_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_REDIRECT_URI: string;
	LIFF_SECRET_KEY: string;
}
